# Site settings
baseurl = "http://marktozzi.com/"
languageCode = "en-us"
title = "Images by Mark Tozzi"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = false
    title = "Images by Mark Tozzi"
    # subtitle = "Photographs from my wanderings"
    author = "Mark Tozzi"
    description = "Landscape photographs, mainly of watefalls"
    keywords = "photographs, landscapes, waterfalls, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    # footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io), [Pavel](https://themes.gohugo.io/hugrid/) and [me](https://chen-zhe.github.io)."
    footertext = "Copyright (C) 2020 by Mark Tozzi"
