# Site settings
baseurl = "https://marktozzi.com/"
languageCode = "en-us"
title = "Images by Mark Tozzi"
theme = "autophugo"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[Author]
    name = "Mark Tozzi"

[params]
    # Image Sizing
    thumb_width = 600
    thumb_quality = 100
    full_size = "1200x1200 q100"
    full_resize_method = "Fit"
    # Layout
    column_count = 4
    
